# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e9e0fb552e51b757a80bd4730bfdc05eda092f2f9776850fbc9129e175ced11766b6f88a98e0f821c8a35cf8d21ea75c9c05d4b12e041a63eabd81f0c963b11a

test:
  secret_key_base: 2b59070cb483455881ce9f0e66627ca572e8aad60dadf2824af2e6cda770fae593e5627eeedf2a6d284ad875b6ee9569133e0cca99efb10568a24359fe016267

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
